external_components:
  - source: github://tobias-93/esphome-ecodan-heatpump@main
    components: [ ecodan ]

logger:
  baud_rate: 0

api:

ota:

wifi:
# remove leading '#' and fill in your wifi details
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendlyName} Fallback Hotspot"

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  id: ecodan_uart
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3
  rx_buffer_size: 1024
  parity: EVEN

ecodan:
  id: ecodan_instance
  uart_id: ecodan_uart

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID
  - platform: ecodan
    date_time:
      name: Current date/time
    defrost:
      name: Defrost
    heating_stage:
      name: Heating stage
    operating_mode:
      name: Operating mode
    heat_cool:
      name: Heating/cooling
    hot_water_timer:
      name: Hot water timer
    date_energy_cons:
      name: Date energy consumption
    date_energy_prod:
      name: Date energy production      
    holiday_mode:
      name: Holiday mode

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
  - platform: ecodan
    error_code:
      name: Error code
    frequency:
      name: Frequency
    output_power:
      name: Output power
    zone1_room_temperature:
      name: Room temperature
    gas_return_temp_signed:
      name: Gas return temperature
    outside_temperature:
      name: Outside temperature
    water_feed_temp_signed:
      name: Water feed temperature
    water_return_temp_signed:
      name: Water return temperature
    mix_tank_feed_temp:
      name: Mixer tank feed temp
    mix_tank_return_temp:
      name: Mixer tank return temp
    hot_water_temperature:
      name: Hot water temperature
    runtime:
      name: Runtime
    water_flow:
      name: Water flow
    energy_cons_yesterday:
      name: Heating energy consumption (yesterday)
    energy_prod_yesterday:
      name: Heating energy production (yesterday)
    energy_cooling_cons_yesterday:
      name: Cooling energy consumption (yesterday)
    energy_cooling_prod_yesterday:
      name: Cooling energy production (yesterday)
    energy_dhw_cons_yesterday:
      name: Hot water energy consumption (yesterday)
    energy_dhw_prod_yesterday:
      name: Hot water energy production (yesterday)

switch:
  - platform: ecodan
    power_state:
      name: Power state
    force_dhw:
      name: Force DHW

select:
  - platform: ecodan
    mode_select:
      name: Mode
    hot_water_mode:
      name: Hot water mode

number:
  - platform: ecodan
    hot_water_setpoint:
      name: Hot water setpoint
    zone1_room_temp_setpoint:
      name: Room temperature setpoint
    zone1_flow_temp_setpoint:
      name: Flow temperature setpoint
